### ISSUE TITLE
Rethink kythera-lib re-exports

### ISSUE THREAD

**Issue by jxs** [polyphene/kythera#59]
## Description

We are currently re-exporting and exposing some `fvm` types via `kythera-lib`. That introduces all sorts of problems when dealing with [breaking changes](https://predr.ag/blog/moving-and-reexporting-rust-type-can-be-major-breaking-change/). We Should probably re-think all re-exports prior to releasing the final version.

**Comment by tchataigner** [comment]
To be fair I do not understand this issue. In the link you are mentioning what is pointed out  is that when using type alias some problems might be created. But we actually never re-import a member of another crate through type aliases. So I think that this does not apply here :thinking:

**Comment by tchataigner** [comment]
Just to give context as to why this was done in the first place:

We have an API which is heavily dependent on the [`ref-fvm`](https://github.com/filecoin-project/ref-fvm) repository as we are interacting with it at a fairly low level. It implies that any crate using our `kythera-lib` will at one point refer to some components of this repository (e.g.: `ApplyRet`...). 

Now, there was multiple methods that we could have used to implement this:
-  (Current) Re-expose from `ref-fvm` all necessary components. This is the simplest one but also mean that we need to bump a major version when the crates of the exposed components do. It also exposes us to versioning mistakes made on the external crates.
- Fix `ref-fvm` crates version. It would ensure that we know what we are dealing with and it would allow us to finely changes from external crates we want to incorporate in our code. However, I think this solution would ask for more time spent on external crate tracking and inspection, while also make us miss some patches on bug fixes.

Then to answer the previous message:

> A major version bump for the dependency will automatically require a major version bump for our crate to, as a type we exposed publicly introduced breaking changes.

This seems ok as we heavily depend on `ref-fvm` anyway and any breaking change on their side will most likely imply it on our side.

> if the crate makes a breaking change to a type in a minor update, it will break our crate as it expects a type and gets a different one.

I do not think that we should go with the assumption that people will badly handle with their versioning but the opposite. Otherwise building with external components becomes impossible.

> common practice to either wrap the types exposed with `newtypes`

I do not see how this protects us from breaking changes of the external crate if its version is not fixed. The `newType` will anyway leverage or expose the external crate and this will break on our next release if there is a new breaking change on the external crate. 

The statement is valid if we're talking about struct wrapping the original one I guess because we can manipulate the interface exposed by it. 

**Conclusion**

We can keep this issue open if we're worried about this. My PoV is that what we did is ok as we are closely linked to `ref-fvm` implementation and there is no ideal way of handling this processus anyway. Plus, I would argue that if we have proper testing of our crates this can be caught ahead of any of our releases, be it minor or major.
